services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434:11434'
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=vectordb'
    labels:
      - 'org.springframework.boot.service-connection=postgres'
    ports:
      - '5432:5432'